config/routes.rb
Rails.application.routes.draw do
  resources :coins
  resources :user_coins
  resources :users, except: [:new, :show, :index]
  root 'welcome#index'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  post '/users' => 'users#create'
  post '/search' => 'coins#search'
  get '/track' => 'twl#tracker'
  post '/track' => 'twl#tracker'
  match "*path" => "coins#index", via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  has_many :user_coins
  has_many :users, through: :user_coins
end

app/models/tracker_sm.rb
class TrackerSm < ApplicationRecord
   def tracker_twl
     account_sid = ENV['ACCOUNT_SID'] # Your Account SID from www.twilio.com/console
     auth_token = ENV['AUTH_TOKEN']   # Your Auth Token from www.twilio.com/console
     @client = Twilio::REST::Client.new account_sid, auth_token
     message = @client.messages.create(
         body: "Hi, Tim. This is Frank talking directly from Ruby",
         to: "7865014449",  # Replace with your phone number
         from: "8285855546")  # Replace with your Twilio number
     puts message.sid
   end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_coins
  has_many :coins, through: :user_coins
  has_secure_password
  before_save { self.email = email.downcase }
  validates :name, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 80 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

end

app/models/user_coin.rb
class UserCoin < ApplicationRecord
  belongs_to :user
  belongs_to :coin

  def current_price
    data = CoinService.new.fetch([self.coin]).first
    data[1][self.coin.symbol.upcase]["USD"]["PRICE"].to_f
  end

  def alert_user
    if user_coin.text_pref == true && user.phone_number == !nil
      #send text message
    else
      #send email
      PriceAlertMailer.send_alert_email(@user).deliver

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!@current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  def index
    @coins = Coin.all
    response = CoinService.new.fetch(@coins)
    @data = JSON.parse(response.body)
  end

  def search
    @coins = Coin.where("symbol iLIKE ? OR coinname iLIKE ?", "%#{params[:coin_term]}%","%#{params[:coin_term]}%")
    response = CoinService.new.fetch(@coins)
    @data = JSON.parse(response.body)
    render :index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to coins_path
    else
      flash.now[:danger] = 'Email or password is incorrect'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out'
    redirect_to coins_path
  end
end

app/controllers/twl_controller.rb
class TwlController < ApplicationController
   def tracker
     @tracker_twl = TrackerSm.new
     @tracker_twl.tracker_twl
   end
 end

app/controllers/user_coins_controller.rb
class UserCoinsController < ApplicationController
  def index
    @coins = Coin.all
    @user_coins = current_user.coins.all
    response = CoinService.new.fetch(@user_coins)
    @data = JSON.parse(response.body)
  end

 def new
   @user_coin = UserCoin.new
 end

 def edit
 end

 def create
   if params[:coin_id].present?
     @user_coin = UserCoin.new(coin_id: params[:coin_id], user: current_user)
   else
    coins = Coin.find_by_symbol(params[:coin_symbol])
     if coins
       @user_coin = UserCoin.new(user_id: current_user, coin_id: coins)
     else
       coins = Coin.find_by_symbol(params[:coin_symbol])
         if coins.save
           @user_coin = UserCoin.new(user_id: current_user, coin_id: coins)
         else
           @user_coin = nil
         flash[:danger] = "Coin is not available"
         end
     end
   end

   respond_to do |format|
     if @user_coin.save
       flash[:success] = "Coin #{@user_coin.coin.symbol} was successfully added"
       format.html { redirect_to user_coins_path }
       format.json { render :show, status: :created, location: @user_coin }
     else
       format.html { redirect_to coins_path }
       flash[:danger] = "Please log in to track your coins"
       format.html { redirect_to coins_path }
       format.json { render json: @user_coin.errors, status: :unprocessable_entity }
     end
   end
 end

 def update
   respond_to do |format|
     if @user_coin.update(user_coins_params)
       flash[:success] = "Coin was successfully updated."
       format.html { redirect_to @user_coin }
       format.json { render :show, status: :ok, location: @user_coin }
     else
       format.html { render :edit }
       format.json { render json: @user_coin.errors, status: :unprocessable_entity }
     end
   end
 end

 def destroy
    set_user_coin
    if @user_coin.present?
       @user_coin.destroy
    end

   respond_to do |format|
     flash[:success] = "Coin was removed from your tracking list."
     format.html { redirect_to user_coins_path }
     format.json { head :no_content }
   end
 end

 private
   def set_user_coin
     @user_coin = UserCoin.find_by(coin_id: (params[:id]))
   end

   def user_coins_params
     params.require(:user_coin).permit(:user_id, :coin_id)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @coins = Coin.all
    @user_coins = UserCoin.where({ user_id: params[:id] })
    api_endpoint =  "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=#{user_coins}&tsyms=USD"
    url = api_endpoint
    response = HTTParty.get(url)
    @data = JSON.parse(response.body)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Lotta Coin, #{@user.name}!"
      redirect_to coins_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User has been deleted"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :phone_number, :text_pref, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = 'You can only edit your own account'
      redirect_to current_user
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/coins_users_helper.rb
module CoinsUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twl_helper.rb
module TwlHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/index.html.erb
<%= form_tag("/search", {:class => 'search-form'}) do %>
  <form class="search-container">
    <%= text_field_tag :coin_term, nil, placeholder: 'Search for coins', id: "search-bar" %>
    <img class="search-icon" src="http://www.endlessicons.com/wp-content/uploads/2012/12/search-icon.png">
  </form>
<% end %>

<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col" class="no-mobile">Logo</th>
      <th scope="col">Market</th>
      <th scope="col" class="no-mobile">Open</th>
      <th scope="col" class="no-mobile">High</th>
      <th scope="col" class="no-mobile">Low</th>
      <th scope="col">Change</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    <% user_coins = [] %>
    <% @data["DISPLAY"].each do |k, v| %>
      <tr>
        <td class="no-mobile">
          <img src="<%= @coins.find_by(name: k).imageurl %>" alt="profile_img" width="35px">
        </td>
        <td class="no-mobile"><%= @coins.find_by(name: k).fullname %></td>
        <td class='large'><%= @coins.find_by(name: k).name %></td>
        <td class="no-mobile"><%= v["USD"]["OPENDAY"] %></td>
        <td class="no-mobile"><%= v["USD"]["HIGHDAY"] %></td>
        <td class="no-mobile"><%= v["USD"]["LOWDAY"] %></td>
        <% if v["USD"]["CHANGEPCTDAY"].to_f < 0 %>
          <td class="price"><%=v["USD"]["CHANGEPCTDAY"] %></td>
        <% else %>
          <td class="price">&nbsp<%=v["USD"]["CHANGEPCTDAY"] %></td>
        <% end %>
        <td><%= v["USD"]["PRICE"] %></td>
        <td class="no-mobile"><%= link_to 'Track', user_coins_path(
                                           user_id: current_user,
                                           coin_id: @coins.find_by(name: k).id),
                                           class: 'btn btn-xs btn-success',
                                           method: :post %></td>
        <td class='large'><%= link_to 'Add', user_coins_path(
                                           user_id: current_user,
                                           coin_id: @coins.find_by(name: k).id),
                                           class: 'btn btn-xs btn-success',
                                           method: :post %></td>
        <td class="no-mobile">
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Alerts
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-up"></i></a>
              <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-up"></i></a>
              <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-down"></i></a>
              <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-down"></i></a>
            </div>
          </div>
        </td>
        <td class='large'>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-up"></i></a>
              <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-up"></i></a>
              <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-down"></i></a>
              <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-down"></i></a>
            </div>
          </div>
        </td>
      </tr>
      <% user_coins << k %>
      <% user_coins << v["USD"]["PRICE"] %>
    <% end %>
    <div class="hidden" id="user_coins"><%= user_coins.to_s %></div>
  </tbody>
</table>

<script type="text/javascript">
  $('.price').each(function() {
      if (parseFloat($(this).text()) < 0) {
          $(this).addClass('lowprice');
      }
  });
  (function titleScroller(text) {
      document.title = text;
      setTimeout(function () {
          titleScroller(text.substr(1) + text.substr(0, 1));
      }, 1000);
  }(user_coins.innerHTML.replace(/['"$]+/g, '').replace(/[\[,\]]+/g, ' ')));
</script>

<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-copyright">
    <div class="container-fluid">
        &copy 2018 Copyright: <a href="https://www.cryptocompare.com" target="_blank">CryptoCompare.com </a>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <%= link_to "Lotta ₵oin", coins_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if logged_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your coins", user_coins_path, class: 'dropdown-item' %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Log out', logout_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav my-2 my-lg-0">
          <li class="nav-item active">
            <%= link_to 'Log in', login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
          </li>
        </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lotta Coin</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Dhurjati|Inconsolata:700|Open+Sans:400,600,700|Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,500" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <% unless controller_name == "welcome" %>
       <%= render 'layouts/navigation' %>
    <% end %>

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<div class="row">
  <% if obj.errors.any? %>
    <div class="alert errors">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>
</div>

app/views/user_coins/index.html.erb
<% if current_user %>
  <% if @user_coins.length > 0 %>
    <h3>Your Coins</h3>
    <table class="table table-hover table-dark">
        <% user_coins = [] %>
        <thead>
          <tr>
            <th scope="col" class="no-mobile">Logo</th>
            <th scope="col" class="no-mobile">Market</th>
            <th scope="col" class="large">Coin</th>
            <th scope="col" class="no-mobile">Open</th>
            <th scope="col" class="no-mobile">High</th>
            <th scope="col" class="no-mobile">Low</th>
            <th scope="col">Change</th>
            <th scope="col">Price </th>
          </tr>
        </thead>
        <tbody>
        <% @data["DISPLAY"].each do |k, v| %>
          <tr>
            <td class="no-mobile">
              <img src="<%= @coins.find_by(name: k).imageurl %>" alt="profile_img" width="35px">
            </td>
            <td class="no-mobile"><%= @coins.find_by(name: k).fullname %></td>
            <td class='large'><%= @coins.find_by(name: k).name %></td>
            <td class="no-mobile"><%= v["USD"]["OPENDAY"] %></td>
            <td class="no-mobile"><%= v["USD"]["HIGHDAY"] %></td>
            <td class="no-mobile"><%= v["USD"]["LOWDAY"] %></td>
            <% if v["USD"]["CHANGEPCTDAY"].to_f < 0 %>
              <td class="price"><%=v["USD"]["CHANGEPCTDAY"] %></td>
            <% else %>
              <td class="price">&nbsp<%=v["USD"]["CHANGEPCTDAY"] %></td>
            <% end %>
            <td><%= v["USD"]["PRICE"] %></td>
            <%# if @user.id == current_user.id %>
            <td class="no-mobile"><%= link_to 'Untrack', user_coin_path(@coins.find_by(name: k).id),
                                             method: :delete,
                                             data: { confirm: 'Are you sure?' },
                                             :class => 'btn btn-xs btn-danger' %></td>
            <td class="large"><%= link_to 'Untrack', user_coin_path(@coins.find_by(name: k).id),
                                             method: :delete,
                                             data: { confirm: 'Are you sure?' },
                                             :class => 'btn btn-xs btn-danger' %></td>
             <td class="no-mobile">
               <div class="dropdown show">
                 <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Alerts
                 </a>
                 <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                   <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-up"></i></a>
                   <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-up"></i></a>
                   <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-down"></i></a>
                   <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-down"></i></a>
                 </div>
               </div>
             </td>
             <td class='large'>
               <div class="dropdown show">
                 <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                 <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                   <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-up"></i></a>
                   <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-up"></i></a>
                   <a class="dropdown-item" href="#">15% <i class="fas fa-arrow-down"></i></a>
                   <a class="dropdown-item" href="#">25% <i class="fas fa-arrow-down"></i></a>
                 </div>
               </div>
             </td>
          </tr>
          <% user_coins << k %>
          <% user_coins << v["USD"]["PRICE"] %>
        <% end %>
        <div class= "hidden" id="user_coins"><%= user_coins.to_s %></div>
        <script>
          (function titleScroller(text) {
            document.title = text;
            setTimeout(function () {
                titleScroller(text.substr(1) + text.substr(0, 1));
          }, 500);
          }(user_coins.innerHTML.replace(/['"$]+/g, '').replace(/[\[,\]]+/g, ' ')));
        </script>
    </tbody>
  </table>
  <% else %>
    <div class="row">
      <div class="text-center col-md-12">
        <h3>Add some coins!</h3>
        <%= link_to "Go Search for some coins", coins_path, class: 'signup-link'%>
      </div>
    </div>
  <% end %>
  <script type="text/javascript">
    $('.price').each(function() {
        if (parseFloat($(this).text()) < 0) {
            $(this).addClass('lowprice');
        }
    });
  </script>
<% else %>
  <h3>You must be logged in to view this page</h3>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="card">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <p class='form-title'>Sign Up</p>
    <form class="form-row">
      <div class="col">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", autofocus: true %>
      </div>
      <div class="col">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, id:"inputPhonenumber" , class: "form-control" ,placeholder: "xxx-xxx-xxxx" %>
      </div>
      <div class="col">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :confirm_password %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.submit(@user.new_record? ? 'Sign up' : 'Update your account', class: "btn btn-lg btn-primary btn-block btn-signin") %>
      </div>
      <p class="signup-link"><%= link_to 'Log in', login_path %></p>
    </form>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="card">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <p class='form-title'>Edit Your Profile</p>
    <form class="form-row">
      <div class="col">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", autofocus: true %>
      </div>
      <div class="col">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, id:"inputPhonenumber" , class: "form-control" ,placeholder: "xxx-xxx-xxxx" %>
      </div>
      <div class="col">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :confirm_password %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.submit(@user.new_record? ? 'Sign up' : 'Update your account', class: "btn btn-lg btn-primary btn-block btn-signin") %>
      </div>
      <p class="signup-link"><%= link_to 'Log in', login_path %></p>
    </form>
  <% end %>
</div>

app/views/users/index.html.erb
<p>User's index page</p>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= current_user.name %>'s profile</h1>

<p>Your email is <%= current_user.email %></p>

<%= link_to "Edit profile", edit_user_path(current_user) %>

app/views/welcome/index.html.erb
<div class="welcome">
  <div class="row">
    <h1 class="p-welcome">
      Welcome To Lotta <span id='coin'>¢</span>oin <br>
      Cryptocurrency Tracker
    </h1>
  </div>

  <a href="/coins" id="button">
    Get Started
    <i></i>
  </a>
</div>